name: Build on Push and commit
on: [push, commit]

jobs:
  build:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install all stuff
      run: sudo apt-get install libsfml-dev libcurlpp-dev libcurl4-gnutls-dev cmake
    - name: Make
      run: | 
        set -e;
        mkdir -p build;
        cd build;
        cmake .. -DCMAKE_BUILD_TYPE=DEBUG;
        make;
